version: "3"

services:
  database:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
      - 3306:3306
    volumes:
      - strapi-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

volumes:
  strapi-data:
